name: movies
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get:
  dio:
  freezed_annotation:
  json_annotation: 4.6.0
  flutter_spinkit: 5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  freezed:
  build_runner: 2.2.0
  json_serializable: 6.3.1

flutter:
  uses-material-design: true